### ISSUE TITLE
how do you open the program

### ISSUE THREAD

**Issue by Pizza2d1** [Ethanscharlie/charlie2d#19]
I couldn't find anything that is shown to be the main executable, neither in the docs or README.md, please make it obvious for us lowly peons my liege, we will sucky-wucky your toes for this great gain

**Comment by Ethanscharlie** [comment]
Its not an executable its a library, there are instructions on the project template on how to compile the template.

**Comment by Ethanscharlie** [comment]
![image](https://github.com/user-attachments/assets/3117336c-90da-49ff-b42e-42c77815b879)

**Comment by Pizza2d1** [comment]
Ok, silly little question, what if some dumbass came upon this project and didn't know how to use it, hypothetically they are really confused, how would they be able to run it?

**Comment by Ethanscharlie** [comment]
Go to the template, clone it, and follow the compilation instructions

**Comment by Pizza2d1** [comment]
Ill try it later as it's not working for me, specifically the ./index not being found at the end
![image_2024-11-06_121004463](https://github.com/user-attachments/assets/74a1b7de-2802-44e4-8b10-cdbea4c22037)

**Comment by Ethanscharlie** [comment]
Looks like a major issue, I'll open a vm and try to recreated this, I'm pretty sure its just a cmake thing. In the meantime installing the sdl2_image/mixer/ttf/gfx libraries to your system should fix the issue `apt install libsdl2-image-dev`. The .so files are included but I think cmake it only looking in the system and not in the correct place

**Comment by Ethanscharlie** [comment]
Issue reproduced, looks like a dependency issue for A LOT of .so files, not sure if I'm going to include them or just tell people to install sdl2_image and sdl2_ttf

**Comment by Ethanscharlie** [comment]
You are now required to install the dependencies to compile a charlie2D project
